[2022-08-08 17:12:53,160] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: training_pipeline_dag.train_data manual__2022-08-08T17:12:49.227024+00:00 [queued]>
[2022-08-08 17:12:53,171] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: training_pipeline_dag.train_data manual__2022-08-08T17:12:49.227024+00:00 [queued]>
[2022-08-08 17:12:53,171] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-08 17:12:53,171] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-08 17:12:53,171] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-08 17:12:53,187] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): train_data> on 2022-08-08 17:12:49.227024+00:00
[2022-08-08 17:12:53,193] {standard_task_runner.py:52} INFO - Started process 91 to run task
[2022-08-08 17:12:53,197] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'training_pipeline_dag', 'train_data', 'manual__2022-08-08T17:12:49.227024+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpouv0ksqp', '--error-file', '/tmp/tmpshicndii']
[2022-08-08 17:12:53,198] {standard_task_runner.py:80} INFO - Job 53: Subtask train_data
[2022-08-08 17:12:53,264] {task_command.py:371} INFO - Running <TaskInstance: training_pipeline_dag.train_data manual__2022-08-08T17:12:49.227024+00:00 [running]> on host b120d11b1074
[2022-08-08 17:12:53,338] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Gibran Otazo
AIRFLOW_CTX_DAG_ID=training_pipeline_dag
AIRFLOW_CTX_TASK_ID=train_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-08T17:12:49.227024+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-08T17:12:49.227024+00:00
[2022-08-08 17:12:53,374] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/training/preprocessing.py", line 60, in create_training_dataset
    df = df.join([embark_dummies_titanic, sex_dummies_titanic, pclass_dummies_titanic, title_dummies_titanic])
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 9100, in join
    other, on=on, how=how, lsuffix=lsuffix, rsuffix=rsuffix, sort=sort
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 9154, in _join_compat
    frames, axis=1, join="outer", verify_integrity=True, sort=sort
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 479, in __init__
    self.new_axes = self._get_new_axes()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 551, in _get_new_axes
    for i in range(ndim)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 551, in <listcomp>
    for i in range(ndim)
  File "pandas/_libs/properties.pyx", line 37, in pandas._libs.properties.CachedProperty.__get__
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 611, in _get_concat_axis
    self._maybe_check_integrity(concat_axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 619, in _maybe_check_integrity
    raise ValueError(f"Indexes have overlapping values: {overlap}")
ValueError: Indexes have overlapping values: Index(['Class_1', 'Class_2', 'Class_3'], dtype='object')
[2022-08-08 17:12:53,384] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=training_pipeline_dag, task_id=train_data, execution_date=20220808T171249, start_date=20220808T171253, end_date=20220808T171253
[2022-08-08 17:12:53,393] {standard_task_runner.py:97} ERROR - Failed to execute job 53 for task train_data (Indexes have overlapping values: Index(['Class_1', 'Class_2', 'Class_3'], dtype='object'); 91)
[2022-08-08 17:12:53,407] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-08 17:12:53,466] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
